name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test -- --coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Check coverage thresholds
      run: |
        COVERAGE_OUTPUT=$(npm run test -- --coverage)
        
        # Extract coverage percentages
        STATEMENTS=$(echo "$COVERAGE_OUTPUT" | grep "All files" | awk '{print $2}' | tr -d '%')
        BRANCHES=$(echo "$COVERAGE_OUTPUT" | grep "All files" | awk '{print $3}' | tr -d '%')
        FUNCTIONS=$(echo "$COVERAGE_OUTPUT" | grep "All files" | awk '{print $4}' | tr -d '%')
        LINES=$(echo "$COVERAGE_OUTPUT" | grep "All files" | awk '{print $5}' | tr -d '%')
        
        # Check against thresholds
        THRESHOLD=80
        
        if (( $(echo "$STATEMENTS < $THRESHOLD" | bc -l) )); then
          echo "Statement coverage ($STATEMENTS%) is below threshold ($THRESHOLD%)"
          exit 1
        fi
        
        if (( $(echo "$BRANCHES < $THRESHOLD" | bc -l) )); then
          echo "Branch coverage ($BRANCHES%) is below threshold ($THRESHOLD%)"
          exit 1
        fi
        
        if (( $(echo "$FUNCTIONS < $THRESHOLD" | bc -l) )); then
          echo "Function coverage ($FUNCTIONS%) is below threshold ($THRESHOLD%)"
          exit 1
        fi
        
        if (( $(echo "$LINES < $THRESHOLD" | bc -l) )); then
          echo "Line coverage ($LINES%) is below threshold ($THRESHOLD%)"
          exit 1
        fi 